METR-LA:
   data : 'data/METR-LA'
   adjdata : False
   gaf_mid_ch : 128
   num_graphs : 12
   num_nodes : 207
   blocks : 4
   layers : 2
   epochs : 100
   input_dim : 2
   input_length : 12 
   output_length : 12
   nhid : 32
   learning_rate : 0.001

PEMS-BAY:
   data : 'data/PEMS-BAY'
   adjdata : False
   gaf_mid_ch : 32
   num_graphs : 9
   num_nodes : 325
   blocks : 4
   layers : 2
   epochs : 100
   input_dim : 2
   input_length : 12 
   output_length : 12
   nhid : 32
   learning_rate : 0.001

NASDAQ10:
   data : 'data/NASDAQ10'
   adjdata : False
   gaf_mid_ch : 256
   num_graphs : 3
   num_nodes : 10
   blocks : 4
   layers : 3
   epochs : 300
   input_dim : 1
   input_length : 15 
   output_length : 5
   nhid : 32
   learning_rate : 0.0001

NASDAQ50:
   data : 'data/NASDAQ50'
   adjdata : False
   gaf_mid_ch : 64
   num_graphs : 6
   num_nodes : 50
   blocks : 4
   layers : 3
   epochs : 300
   input_dim : 1
   input_length : 15 
   output_length : 5
   nhid : 32
   learning_rate : 0.0001

EXCHANGE_H3:
   data : 'data/EXCHANGE_H3'
   adjdata : False
   gaf_mid_ch : 128
   num_graphs : 6
   num_nodes : 8
   blocks : 4
   layers : 6
   epochs : 30
   input_dim : 1
   input_length : 168 
   output_length : 1
   nhid : 32
   learning_rate : 0.0001

EXCHANGE_H6:
   data : 'data/EXCHANGE_H6'
   adjdata : False
   gaf_mid_ch : 256
   num_graphs : 3
   num_nodes : 8
   blocks : 4
   layers : 6
   epochs : 30
   input_dim : 1
   input_length : 168 
   output_length : 1
   nhid : 32
   learning_rate : 0.0001

EXCHANGE_H12:
   data : 'data/EXCHANGE_H12'
   adjdata : False
   gaf_mid_ch : 256
   num_graphs : 9
   num_nodes : 8
   blocks : 4
   layers : 6
   epochs : 50
   input_dim : 1
   input_length : 168 
   output_length : 1
   nhid : 32
   learning_rate : 0.0001

EXCHANGE_H24:
   data : 'data/EXCHANGE_H24'
   adjdata : False
   gaf_mid_ch : 128
   num_graphs : 9
   num_nodes : 8
   blocks : 4
   layers : 6
   epochs : 30
   input_dim : 1
   input_length : 168 
   output_length : 1
   nhid : 32
   learning_rate : 0.0001
   
ELECTRICITY_H3:
   data : 'data/ELECTRICITY_H3'
   adjdata : False
   gaf_mid_ch : 128
   num_graphs : 3
   num_nodes : 321
   blocks : 4
   layers : 4
   epochs : 30
   input_dim : 1
   input_length : 48 
   output_length : 1
   nhid : 16
   learning_rate : 0.0001
   
ELECTRICITY_H6:
   data : 'data/ELECTRICITY_H6'
   adjdata : False
   gaf_mid_ch : 128
   num_graphs : 6
   num_nodes : 321
   blocks : 4
   layers : 4
   epochs : 30
   input_dim : 1
   input_length : 48 
   output_length : 1
   nhid : 16
   learning_rate : 0.0001
   
ELECTRICITY_H12:
   data : 'data/ELECTRICITY_H12'
   adjdata : False
   gaf_mid_ch : 128
   num_graphs : 3
   num_nodes : 321
   blocks : 4
   layers : 4
   epochs : 30
   input_dim : 1
   input_length : 48 
   output_length : 1
   nhid : 16
   learning_rate : 0.0001
   
ELECTRICITY_H24:
   data : 'data/ELECTRICITY_H24'
   adjdata : False
   gaf_mid_ch : 32
   num_graphs : 9
   num_nodes : 321
   blocks : 4
   layers : 4
   epochs : 30
   input_dim : 1
   input_length : 48 
   output_length : 1
   nhid : 16
   learning_rate : 0.0001
   